# Generated by Django 5.1.3 on 2024-11-11 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código del país')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del país')),
                ('phone_code', models.CharField(max_length=10, verbose_name='Código telefónico')),
                ('flag', models.URLField(null=True, verbose_name='URL de la bandera')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='GenderIdentity',
            fields=[
                ('id_genders', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Identidad de género')),
            ],
            options={
                'verbose_name': 'Identidad de género',
                'verbose_name_plural': 'Identidades de género',
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id_marital_statuses', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Estado civil')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civiles',
                'db_table': 'marital_statuses',
            },
        ),
        migrations.CreateModel(
            name='Typesdocs',
            fields=[
                ('id_typedoc', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Código del tipo de documento')),
                ('doc_type', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
                'db_table': 'typesdocs',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de persona')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre de persona')),
                ('surname', models.CharField(max_length=40, verbose_name='Apellido de persona')),
                ('type_email', models.CharField(choices=[('01', 'gmail'), ('02', 'hotmail'), ('03', 'yahoo'), ('04', 'outlook'), ('05', 'icloud')], default='01', max_length=2, verbose_name='Tipo de correo electrónico')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Correo electrónico')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('doc_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Solo se permiten números', regex='^[0-9]*$')], verbose_name='Número de documento')),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten números', regex='^[0-9]*$')], verbose_name='Número de teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.country', verbose_name='País')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.maritalstatus', verbose_name='Estado civil')),
                ('type_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.typesdocs', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coreapp.person', verbose_name='Persona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'user_profiles',
            },
        ),
    ]
